ejohnst2/troveko

app/models/experience.rb
app/models/user.rb

Please review, after you just reviewed.

Experience model validations

---

app/controllers/experiences_controller.rb
app/models/experience.rb
app/views/experiences/create.html.erb
app/views/experiences/destroy.html.erb
app/views/experiences/edit.html.erb
app/views/experiences/index.html.erb
app/views/experiences/new.html.erb
app/views/experiences/show.html.erb
app/views/experiences/update.html.erb
config/routes.rb
db/migrate/20171127171250_add_primary_fields_to_user.rb
db/schema.rb

Experiences controller

---

Gemfile
Gemfile.lock
app/mailers/application_mailer.rb
app/mailers/user_mailer.rb
app/models/user.rb
app/views/layouts/application.html.erb
app/views/user_mailer/welcome.html.erb
app/views/user_mailer/welcome.text.erb
config/environments/development.rb
config/environments/production.rb
db/seeds.rb
test/mailers/previews/user_mailer_preview.rb

Hey bro, email config'd and setup welcome email in the user model. Also sent API keys for PostMark to Heroku for production. Will need to add DKIM and SPF to the domain DNS before sending to actual users, but we've got a base that works for Dev and Production. 
Next step would be to actually think strategically about the email frequency, design, and content but that's beyond the scope of what we need right now perhaps.

Mailer integration

---

app/controllers/experiences_controller.rb
app/models/experience.rb

search function of
experiences
ngo

Searchfunction

---

app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss
app/mailers/user_mailer.rb
app/views/experiences/show.html.erb

Went into the CSS, added a variety of fonts to choose from and chose an initial two for Header and Body. I'm sure we'll iterate through this as we get a more complete picture of look and feel. 
I've also included Troveko brand colors in the css at trov_red, trov_yellow, trov_blue so we can call it anywhere in the program and also overwritten some of the bootstrap defaults.

Font and color scheme

---

app/controllers/application_controller.rb
app/controllers/experiences_controller.rb
app/controllers/pages_controller.rb
app/controllers/reviews_controller.rb
app/controllers/trips_controller.rb
app/helpers/application_helper.rb
app/models/experience.rb
app/views/experiences/index.html.erb
app/views/layouts/application.html.erb
app/views/shared/_flashes.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb

@ejohnst2 added authentication functionality. to be discussed when we really need users to sign in. currently it should be before a booking or before you create a review or experience so we can track what user it belongs to

added authentication and white list and added devise features to navbar

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_new.scss
app/inputs/currency_input.rb
app/inputs/host_story_input.rb
app/models/feature.rb
app/views/experiences/_form.html.erb
app/views/experiences/new.html.erb
db/schema.rb

Hey - did a little re-design on the form for the new view. There is still some work to be done later, but this is a good start. 
I am going to move into working on the features - working through the form made me realize a couple of things in that regard.

create new experience form

---

app/models/activity.rb
app/models/areatype.rb
app/models/areatype_experience.rb
app/models/experience.rb
app/models/experience_activity.rb
app/views/experiences/_activities.html.erb
app/views/experiences/_areatypes.html.erb
app/views/experiences/show.html.erb
db/migrate/20171128174843_create_activities.rb
db/migrate/20171128175021_create_experience_activities.rb
db/migrate/20171128182128_create_areatypes.rb
db/migrate/20171128182347_create_areatype_experiences.rb
db/schema.rb
db/seeds.rb

Hey Alex, can you have a look at this. I created areatypes (ie. farm, desert, mountain, rainforest) as well as activities (ie. hiking, camping, fishing) whereas features will be more of amenities of the accommodation.
All are working when I tested, have a look through.

added areatypes and activities models as well as joiner table

---

app/assets/javascripts/application.js
app/assets/javascripts/channels/conversations.coffee
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/profiles/_show.scss
app/controllers/profiles_controller.rb
app/views/profiles/_empty_experience.html.erb
app/views/profiles/_ngo_profile.html.erb
app/views/profiles/_tabs.html.erb
app/views/profiles/_traveller_profile.html.erb
app/views/profiles/_trip_summary.html.erb
app/views/profiles/show.html.erb
config/routes.rb
db/schema.rb

@ejohnst2 please take a look. need to create some trips now to test this properly

early version of profile page. need trips to test

---

app/assets/stylesheets/components/_navbar.scss
app/controllers/application_controller.rb
app/controllers/funds_controller.rb
app/views/funds/create.html.erb
app/views/funds/destroy.html.erb
app/views/funds/edit.html.erb
app/views/funds/index.html.erb
app/views/funds/new.html.erb
app/views/funds/show.html.erb
app/views/funds/update.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb
db/migrate/20171129225656_add_title_about_use_of_funds_to_fund_model.rb
db/schema.rb

created funding controller, views, and added to the funding model to make it so that ngos can create a fund

Fund controller and model

---

app/controllers/trips_controller.rb
app/views/profiles/_ngo_profile.html.erb
app/views/profiles/_traveller_profile.html.erb
app/views/trips/show.html.erb
config/routes.rb
db/migrate/20171130172152_add_cancel_to_trips.rb
db/schema.rb

@ejohnst2 profile navigation now down including cancellation marker. note that email functionality still needs to be added. lets discuss what should happen on cancellation request

Fixing navigation

---

app/assets/stylesheets/pages/_index_view.scss
app/assets/stylesheets/pages/_show.scss
app/assets/stylesheets/pages/profiles/_show.scss
app/views/experiences/_list.html.erb
app/views/experiences/_sidebar.html.erb
app/views/experiences/show.html.erb
app/views/profiles/_ngo_profile.html.erb
app/views/trips/confirmation.html.erb
db/seeds.rb

Consistency of design and flow

---

app/assets/stylesheets/components/_conversation.scss
app/assets/stylesheets/components/_index.scss
app/controllers/conversations_controller.rb
app/controllers/messages_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/helpers/application_helper.rb
app/models/conversation.rb
app/models/message.rb
app/views/conversations/index.html.erb
app/views/messages/_form.html.erb
app/views/messages/index.html.erb
db/migrate/20171128200112_create_messages.rb

done,please could you check it

Mailboxcreation

---

app/assets/stylesheets/components/_searchfilter.scss
app/views/shared/_searchfilters.html.erb
db/schema.rb

added new experience button to experience page, please check it

Addnewexperiencebuttontoexperiencepage

---

app/assets/stylesheets/pages/_confirmation.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_new_trip.scss
app/assets/stylesheets/pages/profiles/_about.scss
app/views/experiences/_form.html.erb
app/views/experiences/_show_sections.html.erb
app/views/messages/_form.html.erb
app/views/messages/new.html.erb
app/views/orders/show.html.erb
app/views/pages/_team.html.erb
app/views/pages/about.html.erb
app/views/shared/_footer.html.erb
app/views/trips/_form.html.erb
app/views/trips/confirmation.html.erb
app/views/trips/new.html.erb
db/schema.rb

Forms are consistent in their format, what's left is figuring out the right color scheme.

Form consistency

---

app/controllers/trips_controller.rb
app/mailers/user_mailer.rb
app/policies/trip_policy.rb
app/views/shared/_searchfilters.html.erb
app/views/trips/cancel.html.erb
app/views/trips/index.html.erb
app/views/user_mailer/cancel.html.erb
db/schema.rb

cancellation page done,please check it

Cancelation

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/pages/_home.scss
app/views/experiences/_list.html.erb
app/views/profiles/_traveller_profile.html.erb
app/views/shared/_navbar.html.erb

i did the links on the mobile menu, please check it

Responsive

---

app/assets/stylesheets/components/_navbarshow.scss
app/assets/stylesheets/components/_progressbar.scss
app/assets/stylesheets/pages/_show.scss
app/assets/stylesheets/pages/profiles/_show.scss
app/views/experiences/_show_picture_carousel.html.erb
app/views/experiences/_show_sections.html.erb
app/views/experiences/_sidebar.html.erb
app/views/experiences/show.html.erb
app/views/shared/_navbarshow.html.erb

first draft. let's discuss how to design

No sidebar

---

config/meta.yml

Facebook picture size adjusts, please check it

Facebookpicture

---

app/assets/stylesheets/pages/_confirmation.scss
app/assets/stylesheets/pages/_show.scss
app/views/experiences/show.html.erb

The branch name is a little confusing, I did the payment page and the experience show page for mobile view on this branch. I still need to work on the nav bar for the experience show page.

styled the payment and experience show page for mobile views

---

README.md
config/database.yml

update README postgreql janky setup playbook && add host: localhost to
